---
- name: Ensure K3s is running in server mode
  ansible.builtin.shell:
    cmd: "/usr/local/bin/k3s.sh"
  environment:
    INSTALL_K3S_EXEC: "--flannel-iface eth1"
    K3S_KUBECONFIG_MODE: "644"
  register: k3s_server
  when: ansible_facts['services']['k3s.service']['state'] | default('not-found') != "running"

- name: Fetch the kubeconfig file
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ kubeconfig }}"
    mode: 0600
    flat: true
  when: k3s_server.changed

- name: Update server IP in K3s config
  ansible.builtin.replace:
    path: "{{ kubeconfig }}"
    regexp: 'https://127.0.0.1:6443'
    replace: "https://{{ internal_ip }}:6443"
  delegate_to: localhost
  become: false

- name: Ensure all kustomize configs are applied
  kubernetes.core.k8s:
    definition: "{{ lookup('kubernetes.core.kustomize', dir=role_path + '/files/apps/' ) }}"
    namespace: default
    kubeconfig: "{{ kubeconfig }}"
  delegate_to: localhost
  become: false

- name: Ensure ingress config is applied
  kubernetes.core.k8s:
    src: "{{ role_path }}/files/apps/ingress.yml"
    state: present
    namespace: default
    kubeconfig: "{{ kubeconfig }}"
  delegate_to: localhost
  become: false
