---
- name: Ensure K3s is running in server mode
  ansible.builtin.shell:
    cmd: "/usr/local/bin/k3s.sh"
  environment:
    INSTALL_K3S_EXEC: "--flannel-iface eth1"
    K3S_KUBECONFIG_MODE: "644"

- name: Fetch the kubeconfig file
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ kubeconfig }}"
    mode: 0600
    flat: true

- name: Update server IP in K3s config
  ansible.builtin.replace:
    path: "{{ kubeconfig }}"
    regexp: 'https://127.0.0.1:6443'
    replace: "https://{{ internal_ip }}:6443"
  delegate_to: localhost
  become: false

- name: Find all resource config files
  ansible.builtin.find:
    paths: "{{ role_path }}/files/apps/"
    patterns: "*.yml"
    recurse: yes
  register: config_files
  delegate_to: localhost
  become: false

- name: Ensure all resource configs are applied
  kubernetes.core.k8s:
    src: "{{ item.path }}"
    state: present
    namespace: default
    kubeconfig: "{{ kubeconfig }}"
  loop: "{{ config_files.files }}"
  delegate_to: localhost
  become: false
