---
global:
  edition: ce
  ingress:
    configureCertmanager: false
    class: traefik
  hosts:
    domain: app.com
    externalIP: 0.0.0.0
    https: false
certmanager:
  install: false
nginx-ingress:
  enabled: false