---
global:
  edition: ce
  ingress:
    configureCertmanager: false
    class: traefik
  hosts:
    domain: app.com
    externalIP: 172.18.0.2
certmanager:
  install: false
prometheus:
  install: false
gitlab-runner:
  install: false
gitlab-exporter:
  install: false
  enabled: false
nginx-ingress:
  enabled: false
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1