---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-three
data:
  index.html.template: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
          <title>app3.com</title>
      </head>
      <body>
          <h1>Hello from app3.com<h1>
          <p>pod: {{ POD_NAME }}</p>
      </body>
    </html>
