---
- name: Setup K3s server
  hosts: server
  become: true

  vars:
    outfile: ../k3s.yml

  pre_tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - ansible.builtin.import_tasks: 
        file: tasks/get_k3s.yml

  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - curl
          - python3-kubernetes
        state: present

    - name: Ensure K3s is running in server mode
      ansible.builtin.shell:
        cmd: "/usr/local/bin/k3s.sh"
      environment:
        INSTALL_K3S_EXEC: "--flannel-iface eth1"
        K3S_KUBECONFIG_MODE: "644"

    - ansible.builtin.include_tasks: 
        file: tasks/fetch_k3s_conf.yml

    - name: Update server IP in K3s config
      ansible.builtin.replace:
        path: "{{ outfile }}"
        regexp: 'https://127.0.0.1:6443'
        replace: "https://{{ internal_ip }}:6443"
      delegate_to: localhost
      become: false

    - name: Ensure the deployments and ingress are applied
      kubernetes.core.k8s:
        src: "{{ item }}"
        state: present
        namespace: default
        kubeconfig: "{{ outfile }}"
      loop:
        - app1_deployment.yml
        - app2_deployment.yml
        - app3_deployment.yml
        - ingress.yml
      delegate_to: localhost
      become: false