---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-two
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
          <title>Hello from app2.com</title>
      </head>
      <body>
          <h1>Hello from app2.com<h1>
      </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  selector:
    app: app-two
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
spec:
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
        - name: app-two
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
              - name: app-two-config
                mountPath: /usr/share/nginx/html
      volumes:
        - name: app-two-config
          configMap:
            name: app-two