---
- hosts: all

  vars:
    ansible_python_interpreter: /usr/bin/python3.9
    project_src: "/opt/k3s/"

  pre_tasks:
    - name: Add PROJECT_SRC variable in system environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "PROJECT_SRC={{ project_src }}"
        state: present

    - name: Ensure the project directory exists
      ansible.builtin.file:
        path: "{{ project_src }}"
        state: directory

  tasks:
    - name: Ensure the k3s.sh file exists
      ansible.builtin.get_url:
        url: https://get.k3s.io 
        dest: "{{ project_src }}/k3s.sh"
        mode: '0555'

- hosts: servers
  become: true

  vars:
    project_src: "/opt/k3s/"

  tasks:
    - name: Ensure K3s is running in server mode
      ansible.builtin.shell: "{{ project_src }}/k3s.sh"

- hosts: workers
  become: true

  vars:
    project_src: "/opt/k3s/"

  tasks:
    - name: Retrieve K3s token from server
      ansible.builtin.shell:
        cmd: "cat /var/lib/rancher/k3s/server/node-token"
      register: k3s_token
      delegate_to: "{{ hostvars['jlefondeS']['ansible_host'] }}"

    - name: Ensure K3s is running in agent mode
      ansible.builtin.shell:
        cmd: "K3S_URL=https://{{ hostvars['jlefondeS']['ansible_host'] }}:6443 K3S_TOKEN={{ k3s_token }} {{ project_src }}/k3s.sh"