---
- name: Setup K3s server
  hosts: server
  become: true

  roles:
    - role: common
    - role: k3s_server

- name: Setup K3s worker
  hosts: worker
  become: true

  roles:
    - role: common
    - role: k3s_worker
