# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER = "jlefondeS"
SERVER_IP = "192.168.56.110"

WORKER = "jlefondeSW"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provider :virtualbox do |vb|
    vb.cpus = 1
    vb.memory = 1024
  end

  config.vm.define SERVER do |server|
    server.vm.hostname = SERVER
    server.vm.network "private_network", ip: SERVER_IP
    server.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--name", SERVER]
    end
  end

  config.vm.define WORKER do |worker|
    worker.vm.hostname = WORKER
    worker.vm.network "private_network", ip: WORKER_IP
    worker.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--name", WORKER]
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "./confs/provision.yml"
    ansible.groups = {
      "servers" => [SERVER],
      "workers" => [WORKER],
    }
    ansible.host_vars = {
      SERVER => {"internal_ip" => SERVER_IP},
      WORKER => {"internal_ip" => WORKER_IP},
    }
  end
end
