# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.provider :virtualbox do |vb|
    vb.cpus = 1
    vb.memory = 1024
  end

  config.vm.define :jlefondeS do |jlefondeS|
    jlefondeS.vm.hostname = "jlefondeS"
    jlefondeS.vm.network "private_network", ip: "192.168.56.110"
    jlefondeS.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--name", "jlefondeS"]
    end
  end

  config.vm.define :jlefondeSW do |jlefondeSW|
    jlefondeSW.vm.hostname = "jlefondeSW"
    jlefondeSW.vm.network "private_network", ip: "192.168.56.111"
    jlefondeSW.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--name", "jlefondeSW"]
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "./confs/provision.yml"
    ansible.groups = {
      "servers" => ["jlefondeS"],
      "workers" => ["jlefondeSW"],
    }
    ansible.host_vars = {
      "jlefondeS" => {"internal_ip" => "192.168.56.110"},
      "jlefondeSW" => {"internal_ip" => "192.168.56.111"},
    }
  end
end
