---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
        - name: app-three
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-three-html
              mountPath: /usr/share/nginx/html
            - name: app-three-html-template
              mountPath: /usr/share/nginx/html/templates
          env: 
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - /bin/sh
            - -c
            - 'sed "s/{{ POD_NAME }}/$POD_NAME/g" /usr/share/nginx/html/templates/index.html.template > /usr/share/nginx/html/index.html && exec nginx -g "daemon off;"'
      volumes:
        - name: app-three-html-template
          configMap:
            name: app-three
        - name: app-three-html
          emptyDir: {}
