---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-two-config
data:
  index.html.template: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
          <title>app2.com</title>
      </head>
      <body>
          <h1>Hello from app2.com<h1>
          <p>pod: {{ POD_NAME }}</p>
      </body>
    </html>