apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: app-two-config
    target:
      kind: ConfigMap
      name: app-config
  - patch: |-
      - op: replace
        path: /metadata/name
        value: app-two
      - op: replace
        path: /spec/selector/matchLabels/app
        value: app-two
      - op: replace
        path: /spec/template/metadata/labels/app
        value: app-two
      - op: replace
        path: /spec/template/spec/volumes/0/configMap/name
        value: app-two-config
      - op: add
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /metadata/name
        value: app-two
      - op: replace
        path: /spec/selector/app
        value: app-two
    target:
      kind: Service
  - path: configmap_patch.yml
    target:
      kind: ConfigMap