apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: app-three-config
    target:
      kind: ConfigMap
      name: app-config
  - patch: |-
      - op: replace
        path: /metadata/name
        value: app-three
      - op: replace
        path: /spec/selector/matchLabels/app
        value: app-three
      - op: replace
        path: /spec/template/metadata/labels/app
        value: app-three
      - op: replace
        path: /spec/template/spec/volumes/0/configMap/name
        value: app-three-config
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /metadata/name
        value: app-three
      - op: replace
        path: /spec/selector/app
        value: app-three
    target:
      kind: Service
  - path: configmap_patch.yml
    target:
      kind: ConfigMap
