---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-html
              mountPath: /usr/share/nginx/html
            - name: app-html-template
              mountPath: /usr/share/nginx/html/templates
          env: 
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - /bin/sh
            - -c
            - 'sed "s/{{ POD_NAME }}/$POD_NAME/g" /usr/share/nginx/html/templates/index.html.template > /usr/share/nginx/html/index.html && exec nginx -g "daemon off;"'
      volumes:
        - name: app-html-template
          configMap:
            name: app-config
        - name: app-html
          emptyDir: {}
