---
- name: Ensure K3s is running in server mode
  ansible.builtin.shell:
    cmd: "/usr/local/bin/k3s.sh"
  environment:
    INSTALL_K3S_EXEC: "--flannel-iface eth1"
    K3S_KUBECONFIG_MODE: "644"

- name: Fetch the kubeconfig file
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ outfile }}"
    mode: 0600
    flat: true

- name: Update server IP in K3s config
  ansible.builtin.replace:
    path: "{{ outfile }}"
    regexp: 'https://127.0.0.1:6443'
    replace: "https://{{ internal_ip }}:6443"
  delegate_to: localhost
  become: false
  