---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-one
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
          <title>Hello from app1.com</title>
      </head>
      <body>
          <h1>Hello from app1.com<h1>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
        - name: app-one
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
              - name: app-one-config
                mountPath: /usr/share/nginx/html
      volumes:
        - name: app-one-config
          configMap:
            name: app-one