---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
spec:
  selector:
    matchLabels:
      app: app-one
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
        - name: app-one
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: app-one-html
              mountPath: /usr/share/nginx/html
            - name: app-one-html-template
              mountPath: /etc/nginx/templates
          env: 
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - /bin/sh
            - -c
            - 'sed "s/{{ POD_NAME }}/$POD_NAME/g" /etc/nginx/templates/index.html.template > /usr/share/nginx/html/index.html && exec nginx -g "daemon off;"'
      volumes:
        - name: app-one-html-template
          configMap:
            name: app-one
        - name: app-one-html
          emptyDir: {}
